<?php

/**
 * @file
 * Contains anchor_link.module.
 */

use Drupal\Core\Hook\Attribute\LegacyHook;
use Drupal\anchor_link\Hook\AnchorLinkHooks;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
#[LegacyHook]
function anchor_link_help($route_name, RouteMatchInterface $route_match) {
  return \Drupal::service(AnchorLinkHooks::class)->help($route_name, $route_match);
}
